### ISSUE TITLE
All of our work for the past week and a half is gone

### ISSUE THREAD

**Issue by stphnduvall** [stphnduvall/eleanor-vex#1]

**Comment by jhnhnck** [comment]
Check hangouts

**Comment by stphnduvall** [comment]
cant rn

**Comment by jhnhnck** [comment]
There’s a appendages branch and if it’s not there let me know what’s missing and I’ll pull it from the backup

**Comment by stphnduvall** [comment]
![screenshot 2017-11-08 at 9 59 27 am](https://user-images.githubusercontent.com/9062984/32555733-910e8170-c46b-11e7-98cc-b33ce35947f8.png)

**Comment by jhnhnck** [comment]
ac95cd84878b76840868174f9d37660567c820d1
