### ISSUE TITLE
Rebased commits into master and develop should be merges

### ISSUE THREAD

**Issue by jhnhnck** [stphnduvall/eleanor-vex#2]
### Don't push anything into master or develop until this issue is resolved ###
@stphnduvall

**Comment by stphnduvall** [comment]
https://github.com/k88hudson/git-flight-rules#i-made-several-commits-on-a-single-branch-that-should-be-on-different-branches
fuck. we should have used this

**Comment by jhnhnck** [comment]
That's what I did for every single commit...

**Comment by jhnhnck** [comment]
No I'm fixing this... Leave it open until I'm done

**Comment by stphnduvall** [comment]
https://github.com/k88hudson/git-flight-rules#ive-no-idea-what-i-did-wrong

**Comment by jhnhnck** [comment]
Ok I'm about to push a whole bunch of shit including to the appendages branch. You probably want to clone a new repo after I'm done and move your changes over to that. Close this issue when you're ready for me to fuck shit up.

**Comment by jhnhnck** [comment]
Also, I stopped giving a shit about timestamps so everything happened 5 minutes ago. I will fix it eventually it's just a lot of work I don't have time for right now,
